//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBank()
        {
            this.tblBankAccountByPlayers = new HashSet<tblBankAccountByPlayer>();
        }
    
        public System.Guid Id { get; set; }
        public string BankName { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Bin { get; set; }
        public int OrderNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBankAccountByPlayer> tblBankAccountByPlayers { get; set; }
    }
}
