//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankAccountByPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBankAccountByPlayer()
        {
            this.tblWithdraws = new HashSet<tblWithdraw>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PlayerId { get; set; }
        public System.Guid BankId { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankFullName { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool isActive { get; set; }
    
        public virtual tblBank tblBank { get; set; }
        public virtual tblPlayer tblPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWithdraw> tblWithdraws { get; set; }
    }
}
