//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogOfMobileApp
    {
        public System.Guid Id { get; set; }
        public string Source { get; set; }
        public string Data { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
