//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlayer()
        {
            this.tblBankAccountByPlayers = new HashSet<tblBankAccountByPlayer>();
            this.tblDeposits = new HashSet<tblDeposit>();
            this.tblKickOutRooms = new HashSet<tblKickOutRoom>();
            this.tblPlayer_Room = new HashSet<tblPlayer_Room>();
            this.tblRelationships = new HashSet<tblRelationship>();
            this.tblRelationships1 = new HashSet<tblRelationship>();
            this.tblRooms = new HashSet<tblRoom>();
        }
    
        public System.Guid Id { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string GameAccount { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Gender { get; set; }
        public long Credit { get; set; }
        public int GameLevel { get; set; }
        public int PercentOfLevelUp { get; set; }
        public string LastIPAddress { get; set; }
        public Nullable<System.DateTime> LastTimeModified { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int Status { get; set; }
        public bool isVerifiedGameAccount { get; set; }
        public bool isBlock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBankAccountByPlayer> tblBankAccountByPlayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeposit> tblDeposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKickOutRoom> tblKickOutRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlayer_Room> tblPlayer_Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelationship> tblRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelationship> tblRelationships1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoom> tblRooms { get; set; }
    }
}
