//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRoom()
        {
            this.tblPlayer_Room = new HashSet<tblPlayer_Room>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.Guid RoomTypeId { get; set; }
        public long AmountBet { get; set; }
        public System.Guid RoomFeeId { get; set; }
        public string Password { get; set; }
        public int TotalNumOfPlayer { get; set; }
        public int NumOfJoined { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.Guid CreatedByPlayerId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> isTeamWin { get; set; }
        public bool isActive { get; set; }
    
        public virtual tblPlayer tblPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlayer_Room> tblPlayer_Room { get; set; }
        public virtual tblRoomFee tblRoomFee { get; set; }
        public virtual tblRoomType tblRoomType { get; set; }
    }
}
