//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelationship
    {
        public System.Guid Id { get; set; }
        public System.Guid FromPlayer { get; set; }
        public System.Guid ToPlayer { get; set; }
        public Nullable<bool> isFriend { get; set; }
        public bool isBlock { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public bool isActive { get; set; }
    
        public virtual tblPlayer tblPlayer { get; set; }
        public virtual tblPlayer tblPlayer1 { get; set; }
    }
}
