//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole_Permission
    {
        public System.Guid Id { get; set; }
        public string RoleName { get; set; }
        public string PermissionName { get; set; }
    
        public virtual tblPermission tblPermission { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
