//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_Admin.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWithdraw
    {
        public System.Guid Id { get; set; }
        public System.Guid BankAccountByPlayerId { get; set; }
        public long Amount { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    
        public virtual tblBankAccountByPlayer tblBankAccountByPlayer { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
